# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    packageType: 'sdk'

- script: dotnet restore
  displayName: 'Dotnet Restore'

- script: dotnet build --configuration Release
  displayName: 'Dotnet Build'

- script: dotnet test --no-build --verbosity normal
  displayName: 'Dotnet Test'

- script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Dotnet Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

